export enum OrderStatus {
  PENDING = 'PENDING',
  PAID = 'PAID',
  CANCELED = 'CANCELED',
  FAILED = 'FAILED',
  IN_PREPARATION = 'IN_PREPARATION',
  READY_TO_DELIVER = 'READY_TO_DELIVER',
  DONE = 'DONE',
}
